import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../app/style/global.css";
import { Poppins } from "next/font/google";

// Define Poppins font
const poppins = Poppins({
  subsets: ["latin"], // Specify subsets if needed
  weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
  variable: "--font-poppins", // Define as a CSS variable for consistency
});

// Define local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
